// <auto-generated />
using System;
using EcoTurismo.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoTurismo.Infra.Migrations
{
    [DbContext(typeof(EcoTurismoDbContext))]
    [Migration("20260305204105_AddLocalizacaoToAtrativos")]
    partial class AddLocalizacaoToAtrativos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Atrativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único do atrativo");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("CapacidadeMaxima")
                        .HasComment("Capacidade máxima de visitantes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("Descricao")
                        .HasComment("Descrição detalhada do atrativo");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Endereco")
                        .HasComment("Endereço do atrativo");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("Latitude")
                        .HasComment("Latitude do atrativo");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("Longitude")
                        .HasComment("Longitude do atrativo");

                    b.Property<string>("MapUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("MapUrl")
                        .HasComment("URL do mapa (Google Maps, etc)");

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("MunicipioId")
                        .HasComment("FK para o município ao qual o atrativo pertence");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Nome")
                        .HasComment("Nome do atrativo turístico");

                    b.Property<int>("OcupacaoAtual")
                        .HasColumnType("integer")
                        .HasColumnName("OcupacaoAtual")
                        .HasComment("Quantidade atual de visitantes no local");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status")
                        .HasComment("Status do atrativo (ativo, inativo)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("Tipo")
                        .HasComment("Tipo do atrativo (balneario, cachoeira, trilha, parque, fazenda_ecoturismo)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasComment("Data da última atualização do registro");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId")
                        .HasDatabaseName("IX_Atrativos_MunicipioId");

                    b.ToTable("Atrativos", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único do banner");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("Ativo")
                        .HasComment("Indica se o banner está ativo para exibição");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<Guid?>("ImagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ImagemId")
                        .HasComment("FK para a imagem do banner");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("Link")
                        .HasComment("Link de redirecionamento ao clicar no banner");

                    b.Property<Guid?>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("MunicipioId")
                        .HasComment("FK para o município (opcional)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("Ordem")
                        .HasComment("Ordem de exibição do banner");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("text")
                        .HasColumnName("Subtitulo")
                        .HasComment("Subtítulo exibido no banner");

                    b.Property<string>("Titulo")
                        .HasColumnType("text")
                        .HasColumnName("Titulo")
                        .HasComment("Título exibido no banner");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasComment("Data da última atualização do registro");

                    b.HasKey("Id");

                    b.HasIndex("ImagemId")
                        .HasDatabaseName("IX_Banners_ImagemId");

                    b.HasIndex("MunicipioId")
                        .HasDatabaseName("IX_Banners_MunicipioId");

                    b.HasIndex("Ordem")
                        .HasDatabaseName("IX_Banners_Ordem");

                    b.ToTable("Banners", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.ConfiguracaoSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único da configuração");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Chave")
                        .HasComment("Chave única da configuração");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("Descricao")
                        .HasComment("Descrição da finalidade da configuração");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasComment("Data da última atualização do registro");

                    b.Property<string>("Valor")
                        .HasColumnType("text")
                        .HasColumnName("Valor")
                        .HasComment("Valor da configuração");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("ConfiguracoesSistema", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Imagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único da imagem");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Categoria")
                        .HasComment("Categoria da imagem (principal, thumbnail, galeria, logo_login, logo_publico)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("EntidadeId")
                        .HasComment("ID da entidade que possui esta imagem");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("EntidadeTipo")
                        .HasComment("Tipo da entidade que possui esta imagem (ex: Banner, Atrativo, Municipio)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ImagemUrl")
                        .HasComment("URI ou caminho da imagem (base64, URL de OCI, S3, etc)");

                    b.Property<string>("MetadadosJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}")
                        .HasColumnName("MetadadosJson")
                        .HasComment("Metadados da imagem em JSON (nome, tamanho, dimensões, etc)");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("Ordem")
                        .HasComment("Ordem de exibição (para galerias)");

                    b.Property<string>("StorageProvider")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("StorageProvider")
                        .HasComment("Provedor de armazenamento (base64, oci, s3, azure) - Opcional para compatibilidade");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("ThumbnailUrl")
                        .HasComment("URI ou caminho da versão redimensionada (thumbnail/preview)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasComment("Data da última atualização do registro");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Imagens_CreatedAt");

                    b.HasIndex("EntidadeTipo", "EntidadeId")
                        .HasDatabaseName("IX_Imagens_Entidade");

                    b.HasIndex("EntidadeTipo", "EntidadeId", "Categoria")
                        .HasDatabaseName("IX_Imagens_Entidade_Categoria");

                    b.ToTable("Imagens", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único do município");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<Guid?>("LogoAreaPublicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("LogoAreaPublicaId")
                        .HasComment("FK para imagem do logo da área pública");

                    b.Property<Guid?>("LogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("LogoId")
                        .HasComment("FK para imagem do logo geral do município");

                    b.Property<Guid?>("LogoTelaLoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("LogoTelaLoginId")
                        .HasComment("FK para imagem do logo da tela de login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Nome")
                        .HasComment("Nome do município");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("Uf")
                        .HasComment("Unidade federativa (sigla do estado)");

                    b.HasKey("Id");

                    b.HasIndex("LogoAreaPublicaId")
                        .HasDatabaseName("IX_Municipios_LogoAreaPublicaId");

                    b.HasIndex("LogoId")
                        .HasDatabaseName("IX_Municipios_LogoId");

                    b.HasIndex("LogoTelaLoginId")
                        .HasDatabaseName("IX_Municipios_LogoTelaLoginId");

                    b.ToTable("Municipios", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único da permissão");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Action")
                        .HasComment("Ação da permissão (ex: create, read, update, delete)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description")
                        .HasComment("Descrição da finalidade da permissão");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name")
                        .HasComment("Nome completo da permissão (ex: banners:create)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Resource")
                        .HasComment("Recurso da permissão (ex: banners, atrativos)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Permissions_Name");

                    b.HasIndex("Resource", "Action")
                        .IsUnique()
                        .HasDatabaseName("IX_Permissions_Resource_Action");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Quiosque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único do quiosque");

                    b.Property<Guid?>("AtrativoId")
                        .HasColumnType("uuid")
                        .HasColumnName("AtrativoId")
                        .HasComment("FK para o atrativo ao qual o quiosque pertence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("Numero")
                        .HasComment("Número identificador do quiosque");

                    b.Property<int>("PosicaoX")
                        .HasColumnType("integer")
                        .HasColumnName("PosicaoX")
                        .HasComment("Posição X do quiosque no mapa");

                    b.Property<int>("PosicaoY")
                        .HasColumnType("integer")
                        .HasColumnName("PosicaoY")
                        .HasComment("Posição Y do quiosque no mapa");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status")
                        .HasComment("Status do quiosque");

                    b.Property<bool>("TemChurrasqueira")
                        .HasColumnType("boolean")
                        .HasColumnName("TemChurrasqueira")
                        .HasComment("Indica se o quiosque possui churrasqueira");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasComment("Data da última atualização do registro");

                    b.HasKey("Id");

                    b.HasIndex("AtrativoId")
                        .HasDatabaseName("IX_Quiosques_AtrativoId");

                    b.ToTable("Quiosques", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único da reserva");

                    b.Property<Guid>("AtrativoId")
                        .HasColumnType("uuid")
                        .HasColumnName("AtrativoId")
                        .HasComment("FK para o atrativo reservado");

                    b.Property<string>("CidadeOrigem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CidadeOrigem")
                        .HasComment("Cidade de origem do visitante");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("Cpf")
                        .HasComment("CPF do visitante");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("Data")
                        .HasComment("Data de início da reserva");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("DataFim")
                        .HasComment("Data de fim da reserva (para pernoite)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Email")
                        .HasComment("E-mail do visitante");

                    b.Property<string>("NomeVisitante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("NomeVisitante")
                        .HasComment("Nome completo do visitante");

                    b.Property<int>("QuantidadePessoas")
                        .HasColumnType("integer")
                        .HasColumnName("QuantidadePessoas")
                        .HasComment("Quantidade de pessoas na reserva");

                    b.Property<Guid?>("QuiosqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("QuiosqueId")
                        .HasComment("FK para o quiosque reservado (opcional)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status")
                        .HasComment("Status da reserva");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Tipo")
                        .HasComment("Tipo da reserva (day_use, pernoite)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Token")
                        .HasComment("Token único para validação da reserva");

                    b.Property<string>("UfOrigem")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("UfOrigem")
                        .HasComment("UF de origem do visitante");

                    b.HasKey("Id");

                    b.HasIndex("AtrativoId")
                        .HasDatabaseName("IX_Reservas_AtrativoId");

                    b.HasIndex("QuiosqueId");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_Reservas_Token");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único da role");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description")
                        .HasComment("Descrição da finalidade da role");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive")
                        .HasComment("Indica se a role está ativa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name")
                        .HasComment("Nome da role (ex: Admin, Prefeitura)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NormalizedName")
                        .HasComment("Nome normalizado em maiúsculas para busca");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasComment("Data da última atualização do registro");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_NormalizedName");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleId")
                        .HasComment("FK para a role");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("PermissionId")
                        .HasComment("FK para a permissão");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GrantedAt")
                        .HasComment("Data em que a permissão foi concedida à role");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermissions_PermissionId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_RolePermissions_RoleId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único do usuário");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo")
                        .HasComment("Indica se o usuário está ativo no sistema");

                    b.Property<Guid?>("AtrativoId")
                        .HasColumnType("uuid")
                        .HasColumnName("AtrativoId")
                        .HasComment("FK para o atrativo vinculado");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("Cpf")
                        .HasComment("CPF do usuário");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Email")
                        .HasComment("Endereço de e-mail do usuário");

                    b.Property<Guid?>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("MunicipioId")
                        .HasComment("FK para o município vinculado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Nome")
                        .HasComment("Nome completo do usuário");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash")
                        .HasComment("Hash da senha do usuário");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleId")
                        .HasComment("FK para a role do usuário");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Telefone")
                        .HasComment("Telefone do usuário");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasComment("Data da última atualização do registro");

                    b.HasKey("Id");

                    b.HasIndex("AtrativoId");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Cpf")
                        .HasFilter("\"Cpf\" IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_Usuarios_RoleId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Validacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasComment("Identificador único da validação");

                    b.Property<Guid?>("AtrativoId")
                        .HasColumnType("uuid")
                        .HasColumnName("AtrativoId")
                        .HasComment("FK para o atrativo onde ocorreu a validação");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasComment("Data de criação do registro");

                    b.Property<Guid?>("OperadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("OperadorId")
                        .HasComment("FK para o operador que realizou a validação");

                    b.Property<Guid?>("ReservaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ReservaId")
                        .HasComment("FK para a reserva validada");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Token")
                        .HasComment("Token validado");

                    b.Property<bool>("Valido")
                        .HasColumnType("boolean")
                        .HasColumnName("Valido")
                        .HasComment("Indica se o token era válido no momento da validação");

                    b.HasKey("Id");

                    b.HasIndex("AtrativoId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_Validacoes_Token");

                    b.ToTable("Validacoes", (string)null);
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Atrativo", b =>
                {
                    b.HasOne("EcoTurismo.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Atrativos")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Banner", b =>
                {
                    b.HasOne("EcoTurismo.Domain.Entities.Imagem", "Imagem")
                        .WithMany()
                        .HasForeignKey("ImagemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTurismo.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Banners")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Imagem");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("EcoTurismo.Domain.Entities.Imagem", "LogoAreaPublica")
                        .WithMany()
                        .HasForeignKey("LogoAreaPublicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTurismo.Domain.Entities.Imagem", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTurismo.Domain.Entities.Imagem", "LogoTelaLogin")
                        .WithMany()
                        .HasForeignKey("LogoTelaLoginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Logo");

                    b.Navigation("LogoAreaPublica");

                    b.Navigation("LogoTelaLogin");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Quiosque", b =>
                {
                    b.HasOne("EcoTurismo.Domain.Entities.Atrativo", "Atrativo")
                        .WithMany("Quiosques")
                        .HasForeignKey("AtrativoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atrativo");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("EcoTurismo.Domain.Entities.Atrativo", "Atrativo")
                        .WithMany("Reservas")
                        .HasForeignKey("AtrativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoTurismo.Domain.Entities.Quiosque", "Quiosque")
                        .WithMany()
                        .HasForeignKey("QuiosqueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atrativo");

                    b.Navigation("Quiosque");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("EcoTurismo.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoTurismo.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("EcoTurismo.Domain.Entities.Atrativo", "Atrativo")
                        .WithMany()
                        .HasForeignKey("AtrativoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTurismo.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Usuarios")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTurismo.Domain.Entities.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atrativo");

                    b.Navigation("Municipio");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Validacao", b =>
                {
                    b.HasOne("EcoTurismo.Domain.Entities.Atrativo", "Atrativo")
                        .WithMany()
                        .HasForeignKey("AtrativoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTurismo.Domain.Entities.Usuario", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoTurismo.Domain.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atrativo");

                    b.Navigation("Operador");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Atrativo", b =>
                {
                    b.Navigation("Quiosques");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("Atrativos");

                    b.Navigation("Banners");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("EcoTurismo.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
